[package]
name = "oc-rsyncd-bin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Rust implementation of the oc-rsyncd daemon binary"

[[bin]]
name = "oc-rsyncd"
path = "src/main.rs"

[features]
default = []
sd-notify = ["rsync-daemon/sd-notify"]

[dependencies]
rsync-daemon = { path = "../../crates/daemon" }

[target.'cfg(all(windows, target_env = "gnu"))'.dependencies]
rsync-windows-gnu-eh = { path = "../../crates/windows-gnu-eh" }
