name: CI skip interop

on:
  workflow_call:

permissions:
  contents: read

jobs:
  interop-with-upstream:
    name: interop with upstream rsync
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped â€” no code changes"
